# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abf9d36bd0046bb49c0f6a055118d557ea1ea3c7c82483d4d7e51be1c84cdde6bb9adc647105e24a4700fbbfd9adcc7ca7eb7bf2ca06c33997b5621d1cee2df6

test:
  secret_key_base: 4267bd66da85c47ba652ba0295897b28a8855f73381580c86956ed9b0d312bcfa3efc55b6495ca2f5d3f7933d98d43856a0e98287c7df616cfecc34b0c6d2577

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
